=== airbytehq/airbyte/airbyte-integrations/connectors/source-napta/source_napta/schemas/project_contributor.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
      "attributes": {
        "properties": {
          "_mayDelete": {
            "type": "boolean"
          },
          "_mayUpdate": {
            "type": "boolean"
          },
          "contributor_id": {
            "type": "string"
          },
          "created_by_id": {
            "type": "string"
          },
          "created_on": {
            "type": "string"
          },
          "project_id": {
            "type": "string"
          },
          "updated_on": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "id": {
        "type": "string"
      },
      "links": {
        "properties": {
          "self": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": {
        "type": "string"
      }
    },
    "type": "object"
  }

=== airbytehq/airbyte/airbyte-integrations/connectors/source-klaviyo/unit_tests/resource/http/response/email_templates.json
[
  {
    "type": "template",
    "id": "template_001",
    "attributes": {
      "name": "Welcome Email",
      "editor_type": "DRAG_AND_DROP",
      "html": "<html><body><h1>Welcome!</h1></body></html>",
      "text": "Welcome!",
      "created": "2024-01-01T10:00:00+00:00",
      "updated": "2024-01-15T12:30:00+00:00"
    },
    "links": {
      "self": "https://a.klaviyo.com/api/templates/template_001"
    }
  }
]
